### ISSUE TITLE
Without a pillar defined, map.jinja merge was failing.

### ISSUE THREAD

**Issue by mbrindam** [salt-formulas/salt-formula-fluentbit#2]
As we have tiered environments, (dev, prod, staging), but only have defined the pillar for dev at this time, when the formula was pushed to prod, assumingly safely since unused, it caused an issue because the merge approach in the map.jinja was trying to merge a dict with an empty value.  The following error occurred:

```
{%- set fluentbit = salt['grains.filter_by'](base_defaults) %}
{%- do salt['defaults.merge'](fluentbit, salt['pillar.get']('fluentbit')) %} <======================
---
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 418, in render_jinja_tmpl
output = template.render(**decoded_context)
File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in re nder
return self.environment.handle_exception(exc_info, True)
File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in ha ndle_exception
reraise(exc_type, exc_value, tb)
File "<template>", line 1, in top-level template code
File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1013, in m ake_module
return TemplateModule(self, self.new_context(vars, shared, locals))
File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1070, in _ _init__
self._body_stream = list(template.root_render_func(context))
File "/var/cache/salt/minion/files/base/fluentbit/map.jinja", line 35, in top- level template code
{%- do salt['defaults.merge'](fluentbit, salt['pillar.get']('fluentbit')) %}
File "/usr/lib/python2.7/site-packages/salt/modules/defaults.py", line 118, in merge
return dictupdate.update(dest, upd)
File "/usr/lib/python2.7/site-packages/salt/utils/dictupdate.py", line 40, in update
raise TypeError('Cannot update using non-dict types in dictupdate.update()')
TypeError: Cannot update using non-dict types in dictupdate.update()
```

Recommend modifying the merge to this:
```{%- set fluentbit = salt['grains.filter_by']((base_defaults), merge=salt['pillar.get']('fluentbit')) %}```
which is more respectful of there being no pillar present.

**Comment by mbrindam** [comment]
I should add that I had slightly modified the map.jinja to remove the _fluentbit_meta stuff, as we are not using it.  The issue would still stand though.
